version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: mediumclone-postgres
    environment:
      POSTGRES_DB: mediumclone
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - mediumclone-network

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.0
    container_name: mediumclone-elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "9200:9200"
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    networks:
      - mediumclone-network

  app:
    build: .
    container_name: mediumclone-app
    depends_on:
      - postgres
      - elasticsearch
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/mediumclone
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_ELASTICSEARCH_URIS: http://elasticsearch:9200
    ports:
      - "8080:8080"
    volumes:
      - ./uploads:/app/uploads
      - ./backups:/app/backups
    networks:
      - mediumclone-network

volumes:
  postgres_data:
  elasticsearch_data:

networks:
  mediumclone-network:
    driver: bridge 